apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-pedido-deployment
  labels:
    app: fiap-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-pedido
  template:
    metadata:
      labels:
        app: fiap-pedido
    spec:
      containers:
        - name: fiap-pedido
          image: 841162698708.dkr.ecr.us-east-1.amazonaws.com/ms-order:${GITHUB_SHA}
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: DATASOURCE_URL
              value: "jdbc:postgresql://database-1.ctkuimy64klv.us-east-1.rds.amazonaws.com:5432/"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: AWS_REGION
              value: "us-east-1"
            - name: DYNAMODB_TABLE_NAME
              value: "tf-clients-table"
            - name: AWS_SQS_QUEUE_PAYMENT
              value: "https://sqs.us-east-1.amazonaws.com/841162698708/payment-queue"


          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
